run:
  concurrency: 8
  deadline: 10m
  issues-exit-code: 1
  tests: false

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    list-type: blacklist
    packages:
      # logging is allowed only by logutils.Log, logrus
      # is allowed to use only in logutils package
      - github.com/sirupsen/logrus
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - experimental
  gci:
    local-prefixes: github.com/alexandear/final-surge-bot

linters:
  enable-all: true
  disable:
    - goerr113
    - maligned

issues:
  exclude-rules:
    - linters:
        - lll
      source: "^//go:generate "
    - linters:
        - exhaustivestruct
      path: "main.go"
